name: Manual Approval with Auto Tagging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "devmodou@gmail.com"

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo "0.0.0")
        echo "Latest tag: $latest_tag"
        echo "::set-output name=latest_tag::$latest_tag" >> $GITHUB_ENV

    - name: Determine next version
      id: bump_version
      run: |
        # Split the version number into parts
        IFS='.' read -r major minor patch build <<< "${{ needs.build.outputs.latest_tag }}"

        # Increment the build number
        build=$((build + 1))

        # Set the new version as an output
        new_version="$major.$minor.$patch.$build"
        echo "New version: $new_version"
        echo "::set-output name=new_version::$new_version" >> $GITHUB_ENV

    - name: Set deploy_approval input
      run: echo "deploy_approval=${{ github.event.inputs.deploy_approval }}" >> $GITHUB_ENV

  staging-approval:
    runs-on: ubuntu-latest
    environment: 'Staging'
    needs:
      - build
    steps:
      - name: Manual Workflow Approval
        id: manual_approval  
        uses: trstringer/manual-approval@v1.9.0
        timeout-minutes: 1
        with:
          secret: ${{ github.TOKEN }}
          approvers: sencloudpl,MamadouSadio
          minimum-approvals: 1
          issue-title: "Deploying to staging from main"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Get approval decision
        id: approval
        run: echo "::set-output name=decision::${{ steps.manual_approval.outputs.decision }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Store approval decision
        run: echo "APPROVAL_DECISION=${{ steps.approval.outputs.decision }}" >> $GITHUB_ENV

      - name: Use approval decision
        run: |
          if [[ "${APPROVAL_DECISION}" == "yes" ]]; then
            echo "Deployment approved. Proceeding with deployment steps."
            # Ajoutez ici les étapes pour le déploiement
          else
            echo "Deployment not approved. Skipping deployment."
          fi


            

  # create-pull-request:
  #   needs:
  #     - staging-approval
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create Pull Request
  #       if: ${{ needs.build.outputs.latest_tag != '0.0.0' && env.deploy_approval == 'YES' }}
  #       run: |
  #         # Récupérer le nom de la branche actuelle
  #         CURRENT_BRANCH=$(git branch --show-current)
            
  #         # Créer la Pull Request en utilisant l'API GitHub
  #         curl -X POST \
  #           -H "Authorization: token $GITHUB_TOKEN" \
  #           -d '{
  #             "title": "Ma nouvelle Pull Request",
  #             "head": "staging",
  #             "base": "main",
  #             "body": "Description de la Pull Request"
  #           }' \
  #           "https://api.github.com/repos/sencloudpl/workflow/pulls"

      # - name: Fetch the remote changes
      #   run: git fetch origin

      # - name: Merge main into staging
      #   if: ${{ needs.build.outputs.latest_tag != '0.0.0' && env.deploy_approval == 'YES' }}
      #   run: |
      #     # Set up Git for the runner environment (if not already set)
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "devmodou@gmail.com"

      #     # Fetch the remote changes
      #     git fetch origin

      #     # Merge main into staging
      #     git checkout staging
      #     git merge origin/main --no-edit --allow-unrelated-histories
      #     git push origin staging

      #     # Get the new version from the build job output
      #     version="${{ needs.build.outputs.new_version }}"
      #     echo "New version: $version"

      #     # Tag the merge commit with the new version
      #     git tag "$version" "${{ github.sha }}"
      #     git push origin --tags


      # - name: Create Pull Request
      #   if: ${{ needs.build.outputs.latest_tag != '0.0.0' && env.deploy_approval == 'YES' }}
      #   run: |
      #     # Récupérer le nom de la branche actuelle
      #     CURRENT_BRANCH=$(git branch --show-current)
          
      #     # Créer la Pull Request en utilisant l'API GitHub
      #     curl -X POST \
      #       -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #       -d '{
      #         "title": "Ma nouvelle Pull Request",
      #         "head": "staging",
      #         "base": "main",
      #         "body": "Description de la Pull Request"
      #       }' \
      #       "https://api.github.com/repos/sencloudpl/workflow/pulls"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}