name: Manual Approv and Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Mamadou Sadio"
        git config --global user.email "devmodou@gmail.com"
            
    # - uses: trstringer/manual-approval@v1
    #   with:
    #     secret: ${{ github.TOKEN }}
    #     approvers: sencloudpl
    #     minimum-approvals: 1
    #     issue-title: "Deploying v1.3.5 to prod from staging"
    #     issue-body: "Please approve or deny the deployment of version v1.3.5."
    #     exclude-workflow-initiator-as-approver: false
    #     additional-approved-words: 'oui'
    #     additional-denied-words: ''


  staging-approval:
    runs-on: ubuntu-latest
    environment: 'Staging'
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ask for staging deployment approval
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo "Do you want to deploy to staging environment? (YES/NO)"
          read -r confirmation
          echo "INPUT_APPROVAL=$confirmation" >> $GITHUB_ENV

      - name: Check approval and proceed
        if: env.INPUT_APPROVAL == 'YES'
        run: |
          echo "Staging deployment is approved."
          echo "Proceeding with the deployment..."
          git checkout staging
          git merge main
          git push origin staging
        else:
          run: |
            echo "Staging deployment is not approved."
            echo "Skipping the staging deployment..."
