name: Manual Approve and Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Mamadou Sadio"
          git config --global user.email "devmodou@gmail.com"

  staging-check:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ask for staging merging
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Do you want to merge to staging environment? (YES/NO)"
          read -r confirmation

          if [[ $confirmation == "YES" ]]; then
            echo "Staging deployment is approved."
            echo "YES" >> $GITHUB_ENV
          else
            echo "Staging deployment is not approved."
            echo "NO" >> $GITHUB_ENV
          fi

  staging-approval:
    runs-on: ubuntu-latest
    environment: 'Staging'
    needs:
      - build
      - staging-check
    if: needs.staging-check.outputs.approved == 'YES'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ask for staging deployment approval
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Do you want to deploy to staging environment? (YES/NO)"
          read -r confirmation

          if [[ $confirmation == "YES" ]]; then
            echo "Staging deployment is approved."
            echo "YES" >> $GITHUB_ENV
          else
            echo "Staging deployment is not approved."
            echo "NO" >> $GITHUB_ENV
            exit 0
          fi

      - name: Merge main into staging
        if: env.APPROVED == 'YES'
        run: |
          echo Start merge,
          git checkout staging
          git merge main
          git push origin staging
