name: Manual Approv and Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Mamadou Sadio"
        git config --global user.email "devmodou@gmail.com"

    # - name: Increment version or create new tag
    #   id: increment_or_create_tag
    #   run: |
    #     # Retrieve the latest tag (if exists)
    #     LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null)

    #     if [[ -n "$LATEST_TAG" ]]; then
    #       IFS='.' read -r -a VERSION_PARTS <<< "$LATEST_TAG"
    #       NEW_PATCH_VERSION=$((VERSION_PARTS[3]+1))
    #       NEW_TAG="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}.$NEW_PATCH_VERSION"
    #       echo "Latest Tag: $LATEST_TAG"
    #       echo "New Tag: $NEW_TAG"
    #     else
    #       NEW_TAG="0.0.0.1"
    #       echo "No Tags Found. Setting New Tag to: $NEW_TAG"
    #     fi

    #     echo "::set-output name=versioned_tag::$NEW_TAG"

    - name: Create Manual Approval Issue
      uses: toppulous/create-manual-approval-issue@v1

      with:
        token: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
        message: "Please approve the deployment to staging"
        reviewers: "${{ github.actor }}"
        event: "deploy-frontend-approved"
        id: approval

    - name: Check approval status
      run: |
        if [[ "${{ steps.approval.outputs.approved }}" != "true" ]]; then
          echo "Deployment was not approved. Aborting."
          exit 1
        else
          echo "Deployment approved. Proceeding with deployment."
        fi

    - name: Deploy to staging
      run: |
        true

