name: Increment Version and Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config --global user.name "Mamadou Sadio"
        git config --global user.email "devmodou@gmail.com"

    - name: Get latest tag
      id: latest_tag
      run: |
        git fetch --tags
        latestTag=$(git describe --abbrev=0 --tags "0.0.0.*" 2>/dev/null) || latestTag="0.0.0.0"
        echo "Latest tag: $latestTag"
        echo "::set-output name=latest_tag::$latestTag"

    - name: Increment version
      id: increment_version
      run: |
        previousTag=${{ steps.latest_tag.outputs.latest_tag }}
        IFS='.' read -r -a versionParts <<< "${previousTag}"
        nextVersion=$(printf "%d.%d.%d.%d" "${versionParts[0]}" "${versionParts[1]}" "${versionParts[2]}" "$((10#${versionParts[3]} + 1))")
        echo "Next version: $nextVersion"
        echo "::set-output name=next_version::$nextVersion"

    - name: Create and push new tag
      if: ${{ steps.increment_version.outputs.next_version != '0.0.0.0' }}
      run: |
        git tag -a ${{ steps.increment_version.outputs.next_version }} -m "Release ${{ steps.increment_version.outputs.next_version }}"
        git push origin ${{ steps.increment_version.outputs.next_version }}

    - name: Request manual deployment approval
      uses: trstringer/manual-approval@v1
      with:
        token: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
        message: "Please approve the deployment to staging"
        reviewers: "${{ github.actor }}"
        event: "deploy-frontend-approved"
        id: approval

    - name: Check approval status
      run: |
        if [[ "${{ steps.approval.outputs.approved }}" != "true" ]]; then
          echo "Deployment was not approved. Aborting."
          exit 1
        else
          echo "Deployment approved. Proceeding with deployment."
        fi

    - name: Deploy to staging
      run: |
        true

